name: Tick 11:00

on:
  schedule:
    - cron: '0 11 * * *'

jobs:
  hello:
    runs-on: ubuntu-latest
    name: Send a notification
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
      - name: Send a message
        uses: codex-team/action-codexbot-notify@v1
        with:
          webhook: ${{ secrets.CODEX_BOT_CHAT }}
          message: '⏰ 11:00 UTC — ${{ steps.date.outputs.date }}'
          parse_mode: 'markdown'
          disable_web_page_preview: true